<a href="https://colab.research.google.com/github/shahidul-shabuz/Machine-Learning/blob/main/Numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to NumPy**




**NumPy, which stands for "Numerical Python," is a fundamental library for numerical and mathematical operations in Python.** It provides support for working with large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is a core library for scientific computing in Python and is the foundation for many other libraries and tools used in data analysis, machine learning, and scientific research.

**Here are some key features and concepts related to NumPy:**

**Ndarray:** The primary data structure in NumPy is the ndarray, short for "n-dimensional array." It is a versatile data structure that can represent arrays of various dimensions. These arrays are homogeneous, meaning they contain elements of the same data type.

**Array Creation:** You can create NumPy arrays using functions like np.array(), np.zeros(), np.ones(), and np.arange(). You can also create random arrays using np.random functions.

**Array Operations:** NumPy provides a wide range of mathematical and logical operations for element-wise array manipulation. These operations are often more efficient than equivalent operations in standard Python lists.

**Broadcasting:** NumPy allows you to perform operations on arrays of different shapes, and it can automatically broadcast the smaller array to match the shape of the larger one.

**Indexing and Slicing:** You can access and manipulate elements within NumPy arrays using indexing and slicing, similar to standard Python lists.

**Mathematical Functions:** NumPy includes a comprehensive set of mathematical functions, including trigonometric, logarithmic, and exponential functions, as well as linear algebra operations, statistical functions, and more.

**Aggregation and Reduction:** NumPy supports operations for aggregating and reducing arrays, such as sum, mean, median, min, max, and many others.

**Reshaping and Transposing:** You can change the shape and dimensions of arrays using functions like reshape() and transpose().

**File I/O:** NumPy allows you to save and load arrays to/from files using functions like np.save() and np.load().

**Integration with Other Libraries:** NumPy is often used in conjunction with other libraries, such as Pandas for data manipulation and Matplotlib for data visualization.

NumPy is a critical tool in scientific computing and data analysis in Python because it provides fast and efficient operations on large datasets. It is particularly important in fields like data science, machine learning, and scientific research where numerical and mathematical operations on large datasets are common.

NumPy to create a 1 dimensional array, add elements to it & perform some basic operations:

In [ ]:
import numpy as np

# Create a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])
print("Array: ", arr)

# Add elements to the array
arr = np.append(arr, [6, 7, 8])
print("Updated Array: ", arr)

# Basic operations
print("Mean: ", arr.mean())
print("Max: ", arr.max())
print("Min: ", arr.min())
print("Standard Deviation: ", arr.std())


Array:  [1 2 3 4 5]
Updated Array:  [1 2 3 4 5 6 7 8]
Mean:  4.5
Max:  8
Min:  1
Standard Deviation:  2.29128784747792


 NumPy to create a 2-dimensional array, index and slice elements, and perform matrix operations:

In [ ]:
import numpy as np

# Create a 2-dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array: \n", arr)

# Index elements
print("Element at (0, 2): ", arr[0][2])

# Slice elements
print("First two rows: \n", arr[:2])
print("Last two columns: \n", arr[:, -2:])

# Matrix operations
print("Transpose: \n", arr.T)
print("Dot product: \n", np.dot(arr, arr.T))


Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 2):  3
First two rows: 
 [[1 2 3]
 [4 5 6]]
Last two columns: 
 [[2 3]
 [5 6]
 [8 9]]
Transpose: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Dot product: 
 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


NumPy to generate arrays using built-in functions and perform element-wise operations:

In [ ]:
import numpy as np

# Generate arrays using built-in functions
a = np.arange(10)
b = np.linspace(0, 11,11)
c = np.ones((3, 3))
d = np.random.randint(0, 10, (3, 3))

print("a: ", a)
print("b: ", b)
print("c: \n", c)
print("d: \n", d)

# Perform element-wise operations
print("a + b: ", a + b)
print("c * d: \n", c * d)
print("d ** 2: \n", d ** 2)
print("sin(d): \n", np.sin(d))


a:  [0 1 2 3 4 5 6 7 8 9]
b:  [ 0.   1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9 11. ]
c: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
d: 
 [[8 3 9]
 [7 0 7]
 [4 8 6]]


ValueError: ignored

NumPy to demonstrate broadcasting, reshaping and stacking arrays:

In [ ]:
import numpy as np

# Broadcasting
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = a + b
print("a: ", a)
print("b: ", b)
print("c (a + b): ", c)

# Reshaping
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
e = d.reshape(2, 5)
print("d: ", d)
print("e (reshaped d): \n", e)

# Stacking arrays
f = np.array([[1, 2, 3], [4, 5, 6]])
g = np.array([[7, 8, 9], [10, 11, 12]])
h = np.vstack((f, g))
i = np.hstack((f, g))
print("f: \n", f)
print("g: \n", g)
print("h (vertically stacked f and g): \n", h)
print("i (horizontally stacked f and g): \n", i)


a:  [1 2 3]
b:  [10 20 30]
c (a + b):  [11 22 33]
d:  [ 1  2  3  4  5  6  7  8  9 10]
e (reshaped d): 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
f: 
 [[1 2 3]
 [4 5 6]]
g: 
 [[ 7  8  9]
 [10 11 12]]
h (vertically stacked f and g): 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
i (horizontally stacked f and g): 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


NumPy to demonstrate slicing and indexing of arrays:

In [ ]:
import numpy as np

# Slicing and indexing
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = a[:5]
c = a[5:]
d = a[::2]
e = a[::-1]
print("a: ", a)
print("b (a[:5]): ", b)
print("c (a[5:]): ", c)
print("d (a[::2]): ", d)
print("e (a[::-1]): ", e)

f = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
g = f[0, :]
h = f[:, 0]
i = f[1:, 1:]
print("f: \n", f)
print("g (f[0, :]): ", g)
print("h (f[:, 0]): ", h)
print("i (f[1:, 1:]): \n", i)


a:  [ 1  2  3  4  5  6  7  8  9 10]
b (a[:5]):  [1 2 3 4 5]
c (a[5:]):  [ 6  7  8  9 10]
d (a[::2]):  [1 3 5 7 9]
e (a[::-1]):  [10  9  8  7  6  5  4  3  2  1]
f: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
g (f[0, :]):  [1 2 3]
h (f[:, 0]):  [1 4 7]
i (f[1:, 1:]): 
 [[5 6]
 [8 9]]


NumPy to demonstrate statistical operations on arrays:

In [ ]:
import numpy as np

# Statistical operations
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.mean(a)
c = np.median(a)
d = np.std(a)
e = np.var(a)
print("a: ", a)
print("b (mean of a): ", b)
print("c (median of a): ", c)
print("d (standard deviation of a): ", d)
print("e (variance of a): ", e)

f = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
g = np.mean(f, axis=0)
h = np.median(f, axis=1)
i = np.std(f, axis=None)
j = np.var(f, axis=None)
print("f: \n", f)
print("g (mean of f along axis 0): ", g)
print("h (median of f along axis 1): ", h)
print("i (standard deviation of f along axis None): ", i)
print("j (variance of f along axis None): ", j)


a:  [ 1  2  3  4  5  6  7  8  9 10]
b (mean of a):  5.5
c (median of a):  5.5
d (standard deviation of a):  2.8722813232690143
e (variance of a):  8.25
f: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
g (mean of f along axis 0):  [4. 5. 6.]
h (median of f along axis 1):  [2. 5. 8.]
i (standard deviation of f along axis None):  2.581988897471611
j (variance of f along axis None):  6.666666666666667


NumPy to demonstrate matrix operations:

In [ ]:
import numpy as np

# Matrix operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dot(a, b)
d = np.outer(a, b)
e = np.inner(a, b)
print("a: ", a)
print("b: ", b)
print("c (dot product of a and b): ", c)
print("d (outer product of a and b): \n", d)
print("e (inner product of a and b): ", e)

f = np.array([[1, 2], [3, 4]])
g = np.array([[5, 6], [7, 8]])
h = np.matmul(f, g)
i = np.transpose(f)
j = np.linalg.inv(f)
print("f: \n", f)
print("g: \n", g)
print("h (matrix product of f and g): \n", h)
print("i (transpose of f): \n", i)
print("j (inverse of f): \n", j)


a:  [1 2 3]
b:  [4 5 6]
c (dot product of a and b):  32
d (outer product of a and b): 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
e (inner product of a and b):  32
f: 
 [[1 2]
 [3 4]]
g: 
 [[5 6]
 [7 8]]
h (matrix product of f and g): 
 [[19 22]
 [43 50]]
i (transpose of f): 
 [[1 3]
 [2 4]]
j (inverse of f): 
 [[-2.   1. ]
 [ 1.5 -0.5]]


NumPy to demonstrate random number generation:

In [ ]:
import numpy as np

# Random number generation
a = np.random.rand(3)
b = np.random.randn(3)
c = np.random.randint(0, 10, 3)
d = np.random.choice(5, 3, replace=True)
e = np.random.beta(1, 10, 3)
print("a (uniformly distributed random numbers): ", a)
print("b (normally distributed random numbers): ", b)
print("c (random integers between 0 and 10): ", c)
print("d (random samples from [0,1,2,3,4] with replacement): ", d)
print("e (beta-distributed random numbers with alpha=1, beta=10): ", e)

np.random.seed(0)
f = np.random.rand(3)
print("f (random numbers with seed 0): ", f)


a (uniformly distributed random numbers):  [0.30292082 0.04399313 0.4596059 ]
b (normally distributed random numbers):  [-1.7040241   0.06010782  0.53688614]
c (random integers between 0 and 10):  [5 9 6]
d (random samples from [0,1,2,3,4] with replacement):  [4 0 3]
e (beta-distributed random numbers with alpha=1, beta=10):  [0.04658456 0.0331394  0.03579193]
f (random numbers with seed 0):  [0.5488135  0.71518937 0.60276338]


NumPy is important for several reasons:

Efficient array computation: NumPy provides a high-performance multidimensional array object and tools for working with these arrays. It is faster than using Python's built-in list data structure for numerical computations.

Broadcasting: NumPy arrays support broadcasting, which allows performing mathematical operations on arrays of different shapes and sizes.

Array programming: NumPy provides a convenient and efficient way to implement array-oriented computing in Python, which is useful for tasks such as scientific computing, data analysis, and machine learning.

Interoperability: NumPy integrates with other popular Python libraries, such as SciPy, Matplotlib, and Pandas, making it an essential part of the scientific computing stack in Python.

Built-in functions: NumPy provides a large collection of built-in functions for performing operations on arrays, such as mathematical, statistical, and linear algebra operations.

Overall, NumPy is an essential library for anyone working with numerical data in Python, offering a fast and convenient way to perform array-oriented computing.